---
- name: Connection Testing
  hosts: all
  become: yes

  tasks:
  - name: Ping servers
    ping:
  
  - name: Set TimeZone Kyiv
    timezone:
      name: Europe/Kiev

- name: Install Apache on WEB2
  hosts: WEB2
  become: yes

  tasks:
  - name: Update apt packages
    apt: 
      update_cache: yes

  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Start Apache
    service: name=apache2 state=started enabled=yes

- name: Changed index.html
  hosts: web_servers
  become: yes

  tasks:
  - name: copy index
    copy:
        src: ./index.html
        dest: /var/www/html
        mode: 0555
  - name: copy style
    copy:
        src: ./style.css
        dest: /var/www/html
        mode: 0555
    notify: Restart Apache

  handlers:
    - name: Restart Apache
      service: name=apache2 state=restarted



