#!/bin/bash


log=$2

MostRequestFunc () {
echo "Read log.."
awk '{freq[$1]++} END{for (i in freq) print i, freq[i] }' $log | awk '{print $2, "requests from " $1}' | sort -n -r | head -1
}


CountRequestFunc () {
echo "Read log.."
awk '{freq[$1]++} END{for (i in freq) print i, freq[i] }' $log | awk '{print $2, "requests from " $1}' | sort -n
}


MostReqPageFunc () {
echo "Read log..."
awk '{freq[$7]++} END{for (i in freq) print i, freq[i] }' $log | sed '/favicon.ico/d'  |awk '{print $2, "requests from " $1}' | sort -n -r | head -1
}


404PageFunc () {
echo "Read log..."
cat $log | grep " 404 " | grep "http://example" | awk '{print $9, $11}'
}


MostReqTimeFunc () {
echo "Read log..."
awk '{print $4}' $log | sed 's/\[//g' | sed 's/...$//' | awk '{freq[$1]++} END{for (i in freq) print i, freq[i] }' | awk '{print $2, "requests from " $1}' | sort -n -r | head -1
}

    case "$1" in

        -mip) MostRequestFunc ;;
        -mp) MostReqPageFunc  ;;
	-rfip) CountRequestFunc ;;
	-404) 404PageFunc ;;
	-mrt) MostReqTimeFunc ;;
	-r) echo r ;;
        -h) cat ~/log/man ;;
        *) echo "You can use ./parser -h for see all options"
    esac




#Use: ./parcer [-key] (file.log)

# -mip - From which ip were the most requests?

# -mp - What is the most requested page?

# -rfip - How many requests were there from each ip?

# -404 -  What non-existent pages were clients referred to?

# -mrt -  What time did site get the most requests?

# -r - What search bots have accessed the site? (UA + IP)
